projects:
  - id: 479625
    sources:
      - dir: "%crowdin_download_path%"
        crowdinPath:
          dir: "/%branch_name%"
          filename: "entries.json"
        exportPattern:
          dir: "/%branch_name%"
          filename: "%locale_with_underscore%.json"
        includes:
          - pattern: "en_us.json"