modLoader="javafml"
loaderVersion="[28,)"
license="GLGPLv3"

[[mods]] #mandatory
modId="chiselsandbits"
version="${file.jarVersion}"
displayName="Chisels & bits"
authors="OrionOnline, LDTTeam, AlgorithmX2 "
logoFile="logo-forge.png"
description='''
A mod about Sculpting, Decorating and Aesthetics.

Ported to 1.16.x by the LDTTeam.
'''
